import qualquer_coisa


print(dir(qualquer_coisa))
print('INICIO BUILTINS')
print(qualquer_coisa.__builtins__)
print('FIM BUILTINS')
print('INICIO CACHED')
print(qualquer_coisa.__cached__)
print('FIM CACHED')
print('INICIO DOC')
print(qualquer_coisa.__doc__)
print('FIM DOC')
print('INICIO FILE')
print(qualquer_coisa.__file__)
print('FIM FILE')
print('INICIO LOADER')
print(qualquer_coisa.__loader__)
print('FIM LOADER')
print('INICIO NAME')
print(qualquer_coisa.__name__)
print('FIM NAME')
print('INICIO PACKAGE')
print(qualquer_coisa.__package__)
print('FIM PACKAGE')
print('INICIO SPEC')
print(qualquer_coisa.__spec__)
print('FIM SPEC')
help(qualquer_coisa)